const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {JSDOM}=require('jsdom');
const html=fs.readFileSync(path.join(__dirname,'../static/backtest.html'),'utf8');
function setup(fetch){const dom=new JSDOM(html,{url:'http://localhost:8000/backtest',runScripts:'dangerously',beforeParse(w){w.fetch=fetch}});return dom}
function change(w,id,value){const e=w.document.getElementById(id);e.value=value;e.dispatchEvent(new w.Event('change'))}
const tick=()=>new Promise(resolve=>setImmediate(resolve));
function payload(){const strategies={};for(const key of ['max_sharpe','min_variance','target_return','equal_weight'])strategies[key]={status:'ok',metrics:{totalReturn:.1,cagr:.1,volatility:.2,sharpe:.5,maxDrawdown:-.05,turnover:0},nav:[100,110,105],drawdown:[0,0,-.04545],weights:[[.5,.5],[.55,.45],[.52,.48]],rebalances:[{executionDate:'2021-01-04',trainingEnd:'2020-12-31',observations:250,expectedReturn:.1,expectedVolatility:.2,turnover:0}]};return {config:{tickers:['A','B'],mode:'single'},dates:['2021-01-04','2021-01-05','2021-01-06'],strategies,dataSha256:'test-only-data-hash'}}
test('single/rolling and date modes do not send conflicting fields',async()=>{let sent;const dom=setup(async(u,opts)=>{sent=JSON.parse(opts.body);return {ok:true,json:async()=>payload()}}),w=dom.window,d=w.document;change(w,'windowMode','range');assert.equal(d.getElementById('lookback').disabled,true);d.getElementById('form').dispatchEvent(new w.Event('submit',{cancelable:true}));await tick();assert.equal(sent.estimationStart,'2016-01-01');assert.equal(sent.lookbackDays,undefined);change(w,'mode','rolling');change(w,'frequency','weekly');d.getElementById('form').dispatchEvent(new w.Event('submit',{cancelable:true}));await tick();assert.equal(sent.frequency,'weekly');assert.equal(sent.estimationStart,undefined);assert.equal(sent.lookbackDays,1826);dom.window.close()});
test('renders metrics, both charts and selectable drifted weights',async()=>{const dom=setup(async()=>({ok:true,json:async()=>payload()})),w=dom.window,d=w.document;d.getElementById('form').dispatchEvent(new w.Event('submit',{cancelable:true}));await tick();assert.equal(d.querySelectorAll('#metrics tr').length,4);assert.equal(d.querySelectorAll('#equity path').length,4);assert.equal(d.querySelectorAll('#drawdown path').length,4);change(w,'weightDate','1');assert.match(d.getElementById('weights').textContent,/55.00%/);assert.equal(d.getElementById('results').classList.contains('hidden'),false);dom.window.close()});
test('failed strategy excluded from metrics and charts',async()=>{const data=payload();data.strategies.target_return={status:'failed',failureDate:'2021-01-04',error:'Infeasible target'};const dom=setup(async()=>({ok:true,json:async()=>data})),w=dom.window,d=w.document;d.getElementById('form').dispatchEvent(new w.Event('submit',{cancelable:true}));await tick();assert.equal(d.querySelectorAll('#metrics tr').length,3);assert.equal(d.querySelectorAll('#equity path').length,3);assert.match(d.getElementById('failures').textContent,/Infeasible target/);dom.window.close()});
test('API failures show actionable errors and hide stale results',async()=>{let fail=false;const dom=setup(async()=>fail?{ok:false,json:async()=>({detail:'Missing history'})}:{ok:true,json:async()=>payload()}),w=dom.window,d=w.document;d.getElementById('form').dispatchEvent(new w.Event('submit',{cancelable:true}));await tick();fail=true;d.getElementById('form').dispatchEvent(new w.Event('submit',{cancelable:true}));await tick();assert.match(d.getElementById('status').textContent,/Missing history/);assert.equal(d.getElementById('results').classList.contains('hidden'),true);assert.equal(d.getElementById('run').disabled,false);dom.window.close()});
test('submits user holdings and renders them as a comparison strategy',async()=>{let sent;const data=payload();data.strategies.user_holdings={status:'ok',metrics:{totalReturn:.08,cagr:.08,volatility:.18,sharpe:.4,maxDrawdown:-.04,turnover:0},nav:[100,108,106],drawdown:[0,0,-.0185],weights:[[.6,.4],[.62,.38],[.61,.39]],rebalances:[{executionDate:'2021-01-04',trainingEnd:'2020-12-31',observations:250,expectedReturn:.1,expectedVolatility:.2,turnover:0}]};const dom=setup(async(u,opts)=>{sent=JSON.parse(opts.body);return {ok:true,json:async()=>data}}),w=dom.window,d=w.document;d.getElementById('userWeights').value='AAPL=50, MSFT=30, JPM=20';d.getElementById('form').dispatchEvent(new w.Event('submit',{cancelable:true}));await tick();assert.deepEqual(sent.userWeights,{AAPL:.5,MSFT:.3,JPM:.2});assert.equal(d.querySelectorAll('#metrics tr').length,5);assert.match(d.getElementById('metrics').textContent,/Your holdings/);dom.window.close()});
test('curve selection highlights both charts, keyboard inspects dates, visibility can reset',async()=>{const dom=setup(async()=>({ok:true,json:async()=>payload()})),w=dom.window,d=w.document;d.getElementById('form').dispatchEvent(new w.Event('submit',{cancelable:true}));await tick();const path=d.querySelector('#equity path[data-series="max_sharpe"]');path.dispatchEvent(new w.MouseEvent('click',{bubbles:true}));assert.equal(d.querySelector('#drawdown path[data-series="max_sharpe"]').getAttribute('stroke-width'),'3.5');assert.equal(d.querySelector('#equity path[data-series="equal_weight"]').getAttribute('opacity'),'0.22');const selected=d.querySelector('#equity path[data-series="max_sharpe"]');selected.dispatchEvent(new w.KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true}));assert.match(d.querySelector('#equity .chart-readout').textContent,/2021-01-05/);const check=d.querySelector('[aria-label="Show Maximum Sharpe"]');check.checked=false;check.dispatchEvent(new w.Event('change'));assert.equal(d.querySelector('#equity path[data-series="max_sharpe"]'),null);for(const c of d.querySelectorAll('#legend input')){c.checked=false;c.dispatchEvent(new w.Event('change'))}assert.match(d.getElementById('equity').textContent,/All curves are hidden/);[...d.querySelectorAll('#legend button')].find(b=>b.textContent.includes('Show all')).click();assert.equal(d.querySelectorAll('#equity path').length,4);dom.window.close()});
test('pointer inspection uses nearest date and curve',async()=>{const dom=setup(async()=>({ok:true,json:async()=>payload()})),w=dom.window,d=w.document;d.getElementById('form').dispatchEvent(new w.Event('submit',{cancelable:true}));await tick();const svg=d.querySelector('#equity svg');svg.getBoundingClientRect=()=>({left:0,top:0,width:850,height:300});svg.dispatchEvent(new w.MouseEvent('pointermove',{clientX:450,clientY:50}));assert.match(d.querySelector('#equity .chart-readout').textContent,/2021-01-05/);assert.match(d.querySelector('#equity .chart-readout').textContent,/110/);dom.window.close()});
test('comparison explicitly sends original and capped experiment request and exports results',async()=>{let sent,url;const dom=setup(async(u,opts)=>{url=u;sent=JSON.parse(opts.body);return {ok:true,json:async()=>({rows:[],runs:[{status:'failed',lookbackDays:90,frequency:'monthly',variant:'capped',error:'Insufficient history'}],note:'Exploratory'})}}),w=dom.window,d=w.document;d.getElementById('compareCap').value='55';d.getElementById('compare').click();await tick();assert.equal(url,'/api/backtest/compare');assert.equal(sent.cappedWeight,.55);assert.equal(sent.base.mode,'rolling');assert.equal(sent.base.maxWeight,1);assert.match(d.getElementById('comparisonResults').textContent,/Insufficient history/);assert.equal(d.getElementById('compareJson').disabled,false);assert.equal(d.getElementById('compare').disabled,false);dom.window.close()});
test('market display uses local currency and explicit cash assumption',()=>{const dom=setup(async()=>({})),w=dom.window,d=w.document;change(w,'market','CN_SH');assert.match(d.getElementById('capitalLabel').textContent,/CNY/);assert.match(d.getElementById('methodText').textContent,/000001.SS/);assert.match(d.getElementById('methodText').textContent,/0%/);assert.doesNotMatch(d.getElementById('methodText').textContent,/Treasury/);dom.window.close()});
